name: flutter_theme
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  intl: ^0.17.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  injectable: ^1.5.3
  cupertino_icons: ^1.0.2
  provider: ^6.0.2
  intl_utils: ^2.6.1
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1
  dio: ^4.0.4
  google_fonts:
  firebase_core: ^1.17.0
  cloud_firestore: ^3.1.17
  firebase_analytics: ^9.1.9
  json_serializable: ^6.2.0
  get_it: ^7.2.0
  google_sign_in: ^5.3.3
  firebase_auth: ^3.3.19
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  injectable_generator: ^1.5.3
  build_runner: ^2.1.8
  build_resolvers:

flutter:
  uses-material-design: true
  generate: true
  #  To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Open Sans
      fonts:
        - asset: assets/fonts/open_sans/OpenSans-Bold.ttf
        - asset: assets/fonts/open_sans/OpenSans-BoldItalic.ttf
        - asset: assets/fonts/open_sans/OpenSans-ExtraBold.ttf
        - asset: assets/fonts/open_sans/OpenSans-ExtraBoldItalic.ttf
        - asset: assets/fonts/open_sans/OpenSans-Italic.ttf
        - asset: assets/fonts/open_sans/OpenSans-Light.ttf
        - asset: assets/fonts/open_sans/OpenSans-LightItalic.ttf
        - asset: assets/fonts/open_sans/OpenSans-Medium.ttf
        - asset: assets/fonts/open_sans/OpenSans-MediumItalic.ttf
        - asset: assets/fonts/open_sans/OpenSans-Regular.ttf
        - asset: assets/fonts/open_sans/OpenSans-SemiBold.ttf
        - asset: assets/fonts/open_sans/OpenSans-SemiBoldItalic.ttf

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
